import { readFileSync } from "fs"
import { puzToXD } from "../src/puzToXD"
import { xdToJSON } from "xd-crossword-tools-parser"
import { JSONToPuzJSON } from "../src/JSONToPuzJSON"
import { decode as puzDecode } from "../src/vendor/puzjs"
import { it, expect, describe } from "vitest"

describe(JSONToPuzJSON.name, () => {
  it("should convert a JSON object to a PuzJSON object", () => {
    const puz = readFileSync(`./packages/xd-crossword-tools/tests/puz/alpha-bits.puz`)
    const xd = puzToXD(puz)
    const json = xdToJSON(xd)

    json.clues.across[2].metadata = {
      hint: "Second clue!!!",
    }

    const puzJSON = JSONToPuzJSON(json)

    expect(puzJSON).toMatchInlineSnapshot(`
      {
        "author": "Drew Hodson",
        "clues": [
          "Captain of the Pequod",
          "Food for second chance chewing",
          "Font feature // Second clue!!!",
          "Palindromic address to a female",
          "___ Way You Want It",
          "Place often described as humble",
          "Flat two dimensional surface in geometry",
          "Grim homophone of 7D",
          "Off",
          "Heading for some lists",
          "Kanye West is famous for his",
          "Laceration",
          "Alias of Twitch star Richard Tyler Blevins",
          "Capsize",
          "Piece of clothing or print",
          "Evangelical school in Tulsa, OK",
          "___-eyed",
          "Annual",
          "The stamp with the upside down airplane is a famous one",
          "With 42A and Marcus, a luxury department store chain",
          "41A continued",
          "Lush",
          "The Mayan one ended in 2012",
          "What a child often does to their shoes",
          "Vanilla ___",
          "Maligned cigarette ingredient",
          "Frequent cause for a new tire",
          "Los Angeles heavy metal act",
          "Bldgs. such as the Googleplex",
          "A fit of irritation",
          "Lead-in to American or day",
          "What Pokémon do at a Pokémon Center",
          "Nixon's vice",
          "Nothing but ___",
          "One with the world on his shoulders",
          "Filled pastries",
          "Age, in Milan",
          "Lorna ___, novel or cookie",
          "Electrocardiogram readout feature",
          "Hip slang for records",
          "Yiddish for a foolish person",
          "Pc. of concert gear",
          "AI antagonist of 2001",
          "Programming pioneer Lovelace",
          "Prohibit",
          "Type of person to routinely carry a club",
          "State of the ___ Address",
          "Colorful homophone of 18A",
          "Snitched",
          "Kindle fare",
          "Decayed matter",
          "Type of response you hope to get at the altar",
          "Peat-accumulating wetland",
          "The ___, NY art museum",
          "___Fans",
          "Friends, Romans, countrymen, lend me your...",
          ""Friend of Dorothy"",
          "We ___ the Champions",
          "Father of Spider-Man",
          "What a certain applicant becomes",
          "Connect",
          "Particular form of a published text",
          "Suffix at the end of all of Eevee's evolutions",
          "Live and ___ Die",
          "Famous Eastwood whose name became a famous Gorillaz song",
          "Unexpected result in a sporting competition",
          "Disfigure",
          "David Lee and Tim",
          "Luxury watch collection by Garmin",
          "Top dog in an IT org",
          "Sister ___",
          "Author Roald",
          "Civil rights activist Parks",
          "An additional name that could be part of 40D's clue",
          "Director's domain",
          "Type of income to go in a 401k",
          "The Empire Strikes Back, to the Star Wars saga",
          "Greek letter following 72A",
          "Misplace",
          "Wee boy",
          "Dad to Tommy Pickles",
          "The only Patrol I trust",
          "Smart savings plan, briefly",
          "Fresh",
          "Breeds such as Chihuahua or Pomeranian",
          "Bega behind "Mambo No. 5"",
          "Aardvark breakfast",
          "Sonic ___",
        ],
        "copyright": "© 2021",
        "hasState": true,
        "height": 15,
        "note": undefined,
        "sections": [
          {
            "checksum": 10663,
            "data": Uint8Array [
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              0,
              0,
              0,
              0,
              128,
              0,
              128,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
            ],
            "title": "GEXT",
          },
        ],
        "solution": "AHAB..CUD.SERIFMADAM.ANY.ABODEPLANE.DIE.NOTON....TODO.EGO...GASH.NINJA.KEELARTICLE.ORU.DOEYEARLY.MISPRINT..NEI.MAN.SOT..CALENDAR.RETIESICE.TAR.POTHOLEOTEP.HQTRS.SNIT...ALL.HEAL....SPIRO.NET.ATLASTARTS.ETA.DOONEUWAVE.WAX..YUTZ",
        "state": "",
        "title": "Alpha-Bits",
        "width": 15,
      }
    `)
  })
})

it("is good to see what they think of alpha bits", () => {
  const puz = readFileSync(`./packages/xd-crossword-tools/tests/puz/alpha-bits.puz`)
  const a = puzDecode(puz.buffer)

  expect(a).toMatchInlineSnapshot(`
    {
      "circles": [
        0,
        3,
        6,
        8,
        11,
        14,
        60,
        63,
        66,
        68,
        71,
        74,
        111,
        113,
        150,
        153,
        156,
        158,
        161,
        164,
        210,
        213,
        216,
        218,
        221,
        224,
      ],
      "clues": {
        "across": [
          ,
          "Captain of the Pequod",
          ,
          ,
          ,
          "Food for second chance chewing",
          ,
          ,
          "Font feature",
          ,
          ,
          ,
          ,
          "Palindromic address to a female",
          ,
          "___ Way You Want It",
          "Place often described as humble",
          "Flat two dimensional surface in geometry",
          "Grim homophone of 7D",
          "Off",
          "Heading for some lists",
          ,
          "Kanye West is famous for his",
          "Laceration",
          ,
          ,
          ,
          "Alias of Twitch star Richard Tyler Blevins",
          ,
          "Capsize",
          ,
          ,
          ,
          "Piece of clothing or print",
          ,
          "Evangelical school in Tulsa, OK",
          ,
          "___-eyed",
          "Annual",
          "The stamp with the upside down airplane is a famous one",
          ,
          "With 42A and Marcus, a luxury department store chain",
          "41A continued",
          "Lush",
          "The Mayan one ended in 2012",
          ,
          ,
          "What a child often does to their shoes",
          ,
          ,
          "Vanilla ___",
          "Maligned cigarette ingredient",
          "Frequent cause for a new tire",
          "Los Angeles heavy metal act",
          ,
          "Bldgs. such as the Googleplex",
          ,
          "A fit of irritation",
          "Lead-in to American or day",
          ,
          "What Pokémon do at a Pokémon Center",
          ,
          "Nixon's vice",
          ,
          ,
          "Nothing but ___",
          "One with the world on his shoulders",
          ,
          ,
          ,
          ,
          "Filled pastries",
          "Age, in Milan",
          "Lorna ___, novel or cookie",
          "Electrocardiogram readout feature",
          "Hip slang for records",
          "Yiddish for a foolish person",
        ],
        "down": [
          ,
          "Pc. of concert gear",
          "AI antagonist of 2001",
          "Programming pioneer Lovelace",
          "Prohibit",
          "Type of person to routinely carry a club",
          "State of the ___ Address",
          "Colorful homophone of 18A",
          "Snitched",
          "Kindle fare",
          "Decayed matter",
          "Type of response you hope to get at the altar",
          "Peat-accumulating wetland",
          ,
          "The ___, NY art museum",
          ,
          ,
          ,
          ,
          ,
          ,
          "___Fans",
          "Friends, Romans, countrymen, lend me your...",
          ""Friend of Dorothy"",
          "We ___ the Champions",
          "Father of Spider-Man",
          "What a certain applicant becomes",
          ,
          "Connect",
          ,
          "Particular form of a published text",
          "Suffix at the end of all of Eevee's evolutions",
          "Live and ___ Die",
          ,
          "Famous Eastwood whose name became a famous Gorillaz song",
          ,
          "Unexpected result in a sporting competition",
          ,
          ,
          "Disfigure",
          "David Lee and Tim",
          ,
          "Luxury watch collection by Garmin",
          ,
          "Top dog in an IT org",
          "Sister ___",
          "Author Roald",
          "Civil rights activist Parks",
          "An additional name that could be part of 40D's clue",
          "Director's domain",
          ,
          ,
          "Type of income to go in a 401k",
          ,
          "The Empire Strikes Back, to the Star Wars saga",
          ,
          "Greek letter following 72A",
          ,
          ,
          "Misplace",
          ,
          "Wee boy",
          "Dad to Tommy Pickles",
          "The only Patrol I trust",
          "Smart savings plan, briefly",
          "Fresh",
          ,
          "Breeds such as Chihuahua or Pomeranian",
          "Bega behind "Mambo No. 5"",
          "Aardvark breakfast",
          "Sonic ___",
        ],
      },
      "grid": [
        [
          "A",
          "H",
          "A",
          "B",
          ".",
          ".",
          "C",
          "U",
          "D",
          ".",
          "S",
          "E",
          "R",
          "I",
          "F",
        ],
        [
          "M",
          "A",
          "D",
          "A",
          "M",
          ".",
          "A",
          "N",
          "Y",
          ".",
          "A",
          "B",
          "O",
          "D",
          "E",
        ],
        [
          "P",
          "L",
          "A",
          "N",
          "E",
          ".",
          "D",
          "I",
          "E",
          ".",
          "N",
          "O",
          "T",
          "O",
          "N",
        ],
        [
          ".",
          ".",
          ".",
          ".",
          "T",
          "O",
          "D",
          "O",
          ".",
          "E",
          "G",
          "O",
          ".",
          ".",
          ".",
        ],
        [
          "G",
          "A",
          "S",
          "H",
          ".",
          "N",
          "I",
          "N",
          "J",
          "A",
          ".",
          "K",
          "E",
          "E",
          "L",
        ],
        [
          "A",
          "R",
          "T",
          "I",
          "C",
          "L",
          "E",
          ".",
          "O",
          "R",
          "U",
          ".",
          "D",
          "O",
          "E",
        ],
        [
          "Y",
          "E",
          "A",
          "R",
          "L",
          "Y",
          ".",
          "M",
          "I",
          "S",
          "P",
          "R",
          "I",
          "N",
          "T",
        ],
        [
          ".",
          ".",
          "N",
          "E",
          "I",
          ".",
          "M",
          "A",
          "N",
          ".",
          "S",
          "O",
          "T",
          ".",
          ".",
        ],
        [
          "C",
          "A",
          "L",
          "E",
          "N",
          "D",
          "A",
          "R",
          ".",
          "R",
          "E",
          "T",
          "I",
          "E",
          "S",
        ],
        [
          "I",
          "C",
          "E",
          ".",
          "T",
          "A",
          "R",
          ".",
          "P",
          "O",
          "T",
          "H",
          "O",
          "L",
          "E",
        ],
        [
          "O",
          "T",
          "E",
          "P",
          ".",
          "H",
          "Q",
          "T",
          "R",
          "S",
          ".",
          "S",
          "N",
          "I",
          "T",
        ],
        [
          ".",
          ".",
          ".",
          "A",
          "L",
          "L",
          ".",
          "H",
          "E",
          "A",
          "L",
          ".",
          ".",
          ".",
          ".",
        ],
        [
          "S",
          "P",
          "I",
          "R",
          "O",
          ".",
          "N",
          "E",
          "T",
          ".",
          "A",
          "T",
          "L",
          "A",
          "S",
        ],
        [
          "T",
          "A",
          "R",
          "T",
          "S",
          ".",
          "E",
          "T",
          "A",
          ".",
          "D",
          "O",
          "O",
          "N",
          "E",
        ],
        [
          "U",
          "W",
          "A",
          "V",
          "E",
          ".",
          "W",
          "A",
          "X",
          ".",
          ".",
          "Y",
          "U",
          "T",
          "Z",
        ],
      ],
      "meta": {
        "author": "  Drew Hodson  ",
        "copyright": "© 2021",
        "description": "",
        "title": "Alpha-Bits",
      },
      "shades": [],
    }
  `)
})
