import { readFileSync, writeFileSync } from "fs"
import { puzToXD } from "../src/puzToXD"
import { xdToJSON } from "xd-crossword-parser"
import { JSONToPuzJSON } from "../src/JSONToPuzJSON"
// @ts-ignore
import { readpuz } from "@confuzzle/readpuz"
// @ts-ignore
import { writepuz } from "@confuzzle/writepuz"
import { it, expect, describe } from "vitest"

describe(JSONToPuzJSON.name, () => {
  it("should convert a JSON object to a PuzJSON object", () => {
    const puz = readFileSync(`./packages/xd-crossword-tools/tests/puz/alpha-bits.puz`)
    const xd = puzToXD(puz)
    const json = xdToJSON(xd)

    json.clues.across[2].metadata = {
      hint: "Second clue!!!",
    }

    const puzJSON = JSONToPuzJSON(json)
    const puzFile = writepuz(puzJSON)
    writeFileSync(`./packages/xd-crossword-tools/tests/puz/alpha-bits-redo-out.puz`, puzFile)

    expect(puzJSON).toMatchInlineSnapshot(`
      {
        "author": "Drew Hodson",
        "clues": [
          "Captain of the Pequod",
          "Food for second chance chewing",
          "Font feature // Second clue!!!",
          "Palindromic address to a female",
          "___ Way You Want It",
          "Place often described as humble",
          "Flat two dimensional surface in geometry",
          "Grim homophone of 7D",
          "Off",
          "Heading for some lists",
          "Kanye West is famous for his",
          "Laceration",
          "Alias of Twitch star Richard Tyler Blevins",
          "Capsize",
          "Piece of clothing or print",
          "Evangelical school in Tulsa, OK",
          "___-eyed",
          "Annual",
          "The stamp with the upside down airplane is a famous one",
          "With 42A and Marcus, a luxury department store chain",
          "41A continued",
          "Lush",
          "The Mayan one ended in 2012",
          "What a child often does to their shoes",
          "Vanilla ___",
          "Maligned cigarette ingredient",
          "Frequent cause for a new tire",
          "Los Angeles heavy metal act",
          "Bldgs. such as the Googleplex",
          "A fit of irritation",
          "Lead-in to American or day",
          "What Pokémon do at a Pokémon Center",
          "Nixon's vice",
          "Nothing but ___",
          "One with the world on his shoulders",
          "Filled pastries",
          "Age, in Milan",
          "Lorna ___, novel or cookie",
          "Electrocardiogram readout feature",
          "Hip slang for records",
          "Yiddish for a foolish person",
          "Pc. of concert gear",
          "AI antagonist of 2001",
          "Programming pioneer Lovelace",
          "Prohibit",
          "Type of person to routinely carry a club",
          "State of the ___ Address",
          "Colorful homophone of 18A",
          "Snitched",
          "Kindle fare",
          "Decayed matter",
          "Type of response you hope to get at the altar",
          "Peat-accumulating wetland",
          "The ___, NY art museum",
          "___Fans",
          "Friends, Romans, countrymen, lend me your...",
          ""Friend of Dorothy"",
          "We ___ the Champions",
          "Father of Spider-Man",
          "What a certain applicant becomes",
          "Connect",
          "Particular form of a published text",
          "Suffix at the end of all of Eevee's evolutions",
          "Live and ___ Die",
          "Famous Eastwood whose name became a famous Gorillaz song",
          "Unexpected result in a sporting competition",
          "Disfigure",
          "David Lee and Tim",
          "Luxury watch collection by Garmin",
          "Top dog in an IT org",
          "Sister ___",
          "Author Roald",
          "Civil rights activist Parks",
          "An additional name that could be part of 40D's clue",
          "Director's domain",
          "Type of income to go in a 401k",
          "The Empire Strikes Back, to the Star Wars saga",
          "Greek letter following 72A",
          "Misplace",
          "Wee boy",
          "Dad to Tommy Pickles",
          "The only Patrol I trust",
          "Smart savings plan, briefly",
          "Fresh",
          "Breeds such as Chihuahua or Pomeranian",
          "Bega behind "Mambo No. 5"",
          "Aardvark breakfast",
          "Sonic ___",
        ],
        "copyright": "© 2021",
        "hasState": true,
        "height": 15,
        "note": undefined,
        "sections": [
          {
            "checksum": 10663,
            "data": Uint8Array [
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              0,
              0,
              0,
              0,
              128,
              0,
              128,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
              0,
              128,
              0,
              0,
              128,
              0,
              0,
              128,
            ],
            "title": "GEXT",
          },
        ],
        "solution": "AHAB..CUD.SERIFMADAM.ANY.ABODEPLANE.DIE.NOTON....TODO.EGO...GASH.NINJA.KEELARTICLE.ORU.DOEYEARLY.MISPRINT..NEI.MAN.SOT..CALENDAR.RETIESICE.TAR.POTHOLEOTEP.HQTRS.SNIT...ALL.HEAL....SPIRO.NET.ATLASTARTS.ETA.DOONEUWAVE.WAX..YUTZ",
        "state": "",
        "title": "Alpha-Bits",
        "width": 15,
      }
    `)
  })
})

it("is good to see what they think of alpha bits", () => {
  const puz = readFileSync(`./packages/xd-crossword-tools/tests/puz/alpha-bits.puz`)
  const a = readpuz(puz)

  expect(a).toMatchInlineSnapshot(`
    {
      "author": "  Drew Hodson  ",
      "clues": [
        "Captain of the Pequod",
        "Pc. of concert gear",
        "AI antagonist of 2001",
        "Programming pioneer Lovelace",
        "Prohibit",
        "Food for second chance chewing",
        "Type of person to routinely carry a club",
        "State of the ___ Address",
        "Colorful homophone of 18A",
        "Font feature",
        "Snitched",
        "Kindle fare",
        "Decayed matter",
        "Type of response you hope to get at the altar",
        "Peat-accumulating wetland",
        "Palindromic address to a female",
        "The ___, NY art museum",
        "___ Way You Want It",
        "Place often described as humble",
        "Flat two dimensional surface in geometry",
        "Grim homophone of 7D",
        "Off",
        "Heading for some lists",
        "___Fans",
        "Kanye West is famous for his",
        "Friends, Romans, countrymen, lend me your...",
        "Laceration",
        ""Friend of Dorothy"",
        "We ___ the Champions",
        "Father of Spider-Man",
        "What a certain applicant becomes",
        "Alias of Twitch star Richard Tyler Blevins",
        "Connect",
        "Capsize",
        "Particular form of a published text",
        "Suffix at the end of all of Eevee's evolutions",
        "Live and ___ Die",
        "Piece of clothing or print",
        "Famous Eastwood whose name became a famous Gorillaz song",
        "Evangelical school in Tulsa, OK",
        "Unexpected result in a sporting competition",
        "___-eyed",
        "Annual",
        "The stamp with the upside down airplane is a famous one",
        "Disfigure",
        "David Lee and Tim",
        "With 42A and Marcus, a luxury department store chain",
        "41A continued",
        "Luxury watch collection by Garmin",
        "Lush",
        "The Mayan one ended in 2012",
        "Top dog in an IT org",
        "Sister ___",
        "Author Roald",
        "What a child often does to their shoes",
        "Civil rights activist Parks",
        "An additional name that could be part of 40D's clue",
        "Director's domain",
        "Vanilla ___",
        "Maligned cigarette ingredient",
        "Frequent cause for a new tire",
        "Type of income to go in a 401k",
        "Los Angeles heavy metal act",
        "The Empire Strikes Back, to the Star Wars saga",
        "Bldgs. such as the Googleplex",
        "Greek letter following 72A",
        "A fit of irritation",
        "Lead-in to American or day",
        "Misplace",
        "What Pokémon do at a Pokémon Center",
        "Wee boy",
        "Nixon's vice",
        "Dad to Tommy Pickles",
        "The only Patrol I trust",
        "Smart savings plan, briefly",
        "Nothing but ___",
        "Fresh",
        "One with the world on his shoulders",
        "Breeds such as Chihuahua or Pomeranian",
        "Bega behind "Mambo No. 5"",
        "Aardvark breakfast",
        "Sonic ___",
        "Filled pastries",
        "Age, in Milan",
        "Lorna ___, novel or cookie",
        "Electrocardiogram readout feature",
        "Hip slang for records",
        "Yiddish for a foolish person",
      ],
      "copyright": "© 2021",
      "hasState": true,
      "height": 15,
      "note": "",
      "sections": [
        {
          "checksum": 83,
          "data": "0,1",
          "title": "LTIM",
        },
        {
          "checksum": 44010,
          "data": Uint8Array [
            128,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            128,
            0,
            128,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            128,
            0,
            128,
            0,
            0,
            128,
            0,
            0,
            128,
          ],
          "title": "GEXT",
        },
      ],
      "solution": "AHAB..CUD.SERIFMADAM.ANY.ABODEPLANE.DIE.NOTON....TODO.EGO...GASH.NINJA.KEELARTICLE.ORU.DOEYEARLY.MISPRINT..NEI.MAN.SOT..CALENDAR.RETIESICE.TAR.POTHOLEOTEP.HQTRS.SNIT...ALL.HEAL....SPIRO.NET.ATLASTARTS.ETA.DOONEUWAVE.WAX..YUTZ",
      "state": "AHAB..CUD.SERIFMADAM.ANY.ABODEPLANE.DIE.NOTON....TODO.EGO...GASH.NINJA.KEELARTICLE.ORU.DOEYEARLY.MISPRINT..NEI.MAN.SOT..CALENDAR.RETIESICE.TAR.POTHOLEOTEP.HQTRS.SNIT...ALL.HEAL....SPIRO.NET.ATLASTARTS.ETA.DOONEUWAVE.WAX..YUTZ",
      "title": "Alpha-Bits",
      "width": 15,
    }
  `)
})
