import type {
  AmuseTopLevel,
  Copyright,
  Letter,
  Locale,
  PublishTimeZone,
  PuzzleType
} from "../../src/amuseJSONToXD.types"

export const schrodingerAmuseExample: AmuseTopLevel = {
  meta: {},
  data: {
    id: 1,
    attributes: {
        amuse_id: "abcd1234",
        amuse_set: "tny-weekly",
        unsupported: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      amuse_data: {
      h: 5,
      w: 1,
      id: "abcd1234",
      box: [
        [
          "H/J" as Letter,
          "E" as Letter,
          "L" as Letter,
          "L" as Letter,
          "O" as Letter,
        ],
      ],
      help: "",
      tags: [],
      title: "Standard Puzzle",
      author: "Julien Devlin",
      locale: "en-US" as Locale,
      srcJPZ: true,
      tn_url: "",
      checkPDF: false,
      clueNums: [
        [
          "1",
          "0",
          "0",
          "0",
          "0",
        ],
      ],
      problems: [],
      subtitle: "",
      authorURL: "",
      copyright: "" as Copyright,
      showRebus: false,
      endMessage: "",
      isImported: true,
      puzzleType: "CROSSWORD" as PuzzleType,
      targetTime: 0,
      authorEmail: "",
      backdropURL: "",
      bonusPoints: 0,
      boxImageURL: "",
      description: "",
      placedWords: [
        {
          x: 0,
          y: 0,
          clue: {
            clue: "schrodinger clue",
          },
          word: "{H/J}ELLO",
          nBoxes: 5,
          clueNum: "1",
          intersects: false,
          originalTerm: "{H/J}ELLO",
          acrossNotDown: false
        },
      ],
      publishTime: 0,
      srcFileName: "test.jpz",
      allowSharing: false,
      attributions: "",
      checkEnabled: true,
      creationTime: 0,
      hideInPicker: false,
      hintsEnabled: true,
      modifiedTime: 0,
      pauseMessage: "",
      caseSensitive: false,
      letterPenalty: -1,
      preRevealIdxs: [
        [
          false,
          false,
          false,
          false,
          false,
        ],
      ],
      revealEnabled: true,
      shareImageURL: "",
      wrongSoundURL: "",
      correctSoundURL: "",
      hideClueColumns: false,
      publishTimeZone: "Etc/UTC" as PublishTimeZone,
      showStartButton: false,
      correctWordPoints: 0,
      contestModeEnabled: false,
      unlinkGridAndClues: false,
      wordLengthsEnabled: false,
      mediaPreviewEnabled: false,
      boxToPlacedWordsIdxs: [],
      errorCheckModeEnabled: true,
      mediaPreviewAndTextEnabled: true
       } }
  }
}

export const rebusAmuseExample: AmuseTopLevel = {
  meta: {},
  data: {
    id: 1,
    attributes: {
        amuse_id: "abcd1234",
        amuse_set: "tny-weekly",
        unsupported: null,
        createdAt: new Date(),
        updatedAt: new Date(),
      amuse_data: {
      h: 4,
      w: 1,
      id: "abcd1234",
      box: [
        [
          "W" as Letter,
          "O" as Letter,
          "R" as Letter,
          "LD" as Letter,
        ],
      ],
      help: "",
      tags: [],
      title: "Standard Puzzle",
      author: "Julien Devlin",
      locale: "en-US" as Locale,
      srcJPZ: true,
      tn_url: "",
      checkPDF: false,
      clueNums: [
        [
          "1",
          "0",
          "0",
          "0",
        ],
      ],
      problems: [],
      subtitle: "",
      authorURL: "",
      copyright: "" as Copyright,
      showRebus: false,
      endMessage: "",
      isImported: true,
      puzzleType: "CROSSWORD" as PuzzleType,
      targetTime: 0,
      authorEmail: "",
      backdropURL: "",
      bonusPoints: 0,
      boxImageURL: "",
      description: "",
      placedWords: [
        {
          x: 0,
          y: 0,
          clue: {
            clue: "rebus clue",
          },
          word: "WOR{LD}",
          nBoxes: 4,
          clueNum: "1",
          intersects: false,
          originalTerm: "WOR{LD}",
          acrossNotDown: false
        }
      ],
      publishTime: 0,
      srcFileName: "test.jpz",
      allowSharing: false,
      attributions: "",
      checkEnabled: true,
      creationTime: 0,
      hideInPicker: false,
      hintsEnabled: true,
      modifiedTime: 0,
      pauseMessage: "",
      caseSensitive: false,
      letterPenalty: -1,
      preRevealIdxs: [
        [
          false,
          false,
          false,
          false,
        ],
      ],
      revealEnabled: true,
      shareImageURL: "",
      wrongSoundURL: "",
      correctSoundURL: "",
      hideClueColumns: false,
      publishTimeZone: "Etc/UTC" as PublishTimeZone,
      showStartButton: false,
      correctWordPoints: 0,
      contestModeEnabled: false,
      unlinkGridAndClues: false,
      wordLengthsEnabled: false,
      mediaPreviewEnabled: false,
      boxToPlacedWordsIdxs: [],
      errorCheckModeEnabled: true,
      mediaPreviewAndTextEnabled: true
       } }
  }
}
